import { EntitySchema } from "typeorm";

export default new EntitySchema({
  name: "Bill",
  tableName: "bills",
  columns: {
    id: { type: "uuid", primary: true, generated: "uuid" },
    tenantId: { name: "tenant_id", type: "uuid", nullable: true },
    propertyId: { name: "property_id", type: "uuid", nullable: true },
    billingMonth: { name: "billing_month", type: "timestamp", nullable: false },
    rentAmount: { name: "rent_amount", type: "numeric", nullable: true },
    extraCharges: { name: "extra_charges", type: "jsonb", nullable: true },
    extraAmount: { name: "extra_amount", type: "numeric", nullable: true },
    electricityUnit: { name: "electricity_unit", type: "numeric", nullable: true },
    electricityRate: { name: "electricity_rate", type: "numeric", nullable: true },
    electricityBillAmount: {
      name: "electricity_bill_amount",
      type: "numeric",
      nullable: true,
    },
    totalBillAmount: { name: "total_bill_amount", type: "numeric", nullable: true },
    invoiceNo: { name: "invoice_no", type: "varchar", nullable: true },
    billDuration: { name: "bill_duration", type: "integer", nullable: true },
    createdBy: { name: "created_by", type: "uuid", nullable: true },
    note: { type: "text", nullable: true },
    bookingId: { name: "booking_id", type: "uuid", nullable: true },
    companyId: { name: "company_id", type: "uuid", nullable: true },
    totalBillAmountAfterGST: {
      name: "total_bill_amount_after_gst",
      type: "numeric",
      nullable: true,
    },
    totalgst: { name: "totalgst", type: "numeric", nullable: true },
    status: { type: "boolean", default: false },
    paymentType: { name: "payment_type", type: "varchar", nullable: true },
    gstpercent: { name: "gstpercent", type: "numeric", nullable: true },
    isDeleted: { name: "is_deleted", type: "boolean", default: false },
    deletedAt: { name: "deleted_at", type: "timestamp", nullable: true },
    deletedBy: { name: "deleted_by", type: "uuid", nullable: true },
    createdAt: { name: "created_at", type: "timestamp", createDate: true },
    updatedAt: { name: "updated_at", type: "timestamp", updateDate: true },
  },

  relations: {
    tenant: {
      type: "many-to-one",
      target: "Tenant",
      joinColumn: { name: "tenant_id", referencedColumnName: "id" },
      nullable: true,
      onDelete: "RESTRICT",
      onUpdate: "NO ACTION",
    },
    property: {
      type: "many-to-one",
      target: "Property",
      joinColumn: { name: "property_id", referencedColumnName: "id" },
      nullable: true,
      onDelete: "RESTRICT",
      onUpdate: "NO ACTION",
    },
    booking: {
      type: "many-to-one",
      target: "Booking",
      joinColumn: { name: "booking_id", referencedColumnName: "id" },
      nullable: true,
      onDelete: "RESTRICT",
      onUpdate: "NO ACTION",
    },
    company: {
      type: "many-to-one",
      target: "Company",
      joinColumn: { name: "company_id", referencedColumnName: "id" },
      nullable: true,
      onDelete: "RESTRICT",
      onUpdate: "NO ACTION",
    },
    deletedByCompany: {
      type: "many-to-one",
      target: "Company",
      joinColumn: { name: "deleted_by", referencedColumnName: "id" },
      nullable: true,
      onDelete: "SET NULL",
      onUpdate: "NO ACTION",
    },
  },
});