import { EntitySchema } from "typeorm";

export default new EntitySchema({
  name: "Booking",
  tableName: "bookings",
  columns: {
    id: { type: "uuid", primary: true, generated: "uuid" },
    bookingNo: { name: "booking_no", type: "varchar", nullable: true },
    accountName: { name: "account_name", type: "varchar", nullable: true },
    propertyId: { name: "property_id", type: "uuid", nullable: true },
    ownerId: { name: "owner_id", type: "uuid", nullable: true },
    tenantId: { name: "tenant_id", type: "uuid", nullable: true },
    companyId: { name: "company_id", type: "uuid", nullable: true },
    bookingDate: {
      name: "booking_date",
      type: "timestamp",
      default: () => "CURRENT_TIMESTAMP",
    },
    startingDate: { name: "starting_date", type: "timestamp", nullable: true },
    endingDate: { name: "ending_date", type: "timestamp", nullable: true },
    advanceAmount: { name: "advance_amount", type: "numeric", nullable: true },
    rentAmount: { name: "rent_amount", type: "numeric", nullable: true },
    projectId: { name: "project_id", type: "uuid", nullable: true },
    blockId: { name: "block_id", type: "uuid", nullable: true },
    createdBy: { name: "created_by", type: "uuid", nullable: true },
    isDeleted: { name: "is_deleted", type: "boolean", default: false },
    vacantNotice: { name: "vacant_notice", type: "boolean", default: true },
    createdAt: { name: "created_at", type: "timestamp", createDate: true },
    updatedAt: { name: "updated_at", type: "timestamp", updateDate: true },
  },

  relations: {
    property: {
      type: "many-to-one",
      target: "Property",
      joinColumn: { name: "property_id", referencedColumnName: "id" },
      nullable: true,
      onDelete: "RESTRICT",
      onUpdate: "NO ACTION",
    },
    owner: {
      type: "many-to-one",
      target: "Owner",
      joinColumn: { name: "owner_id", referencedColumnName: "id" },
      nullable: true,
      onDelete: "RESTRICT",
      onUpdate: "NO ACTION",
    },
    tenant: {
      type: "many-to-one",
      target: "Tenant",
      joinColumn: { name: "tenant_id", referencedColumnName: "id" },
      nullable: true,
      onDelete: "RESTRICT",
      onUpdate: "NO ACTION",
    },
    company: {
      type: "many-to-one",
      target: "Company",
      joinColumn: { name: "company_id", referencedColumnName: "id" },
      nullable: true,
      onDelete: "RESTRICT",
      onUpdate: "NO ACTION",
    },
    project: {
      type: "many-to-one",
      target: "project",
      joinColumn: { name: "project_id", referencedColumnName: "id" },
      nullable: true,
      onDelete: "SET NULL",
      onUpdate: "NO ACTION",
    },
    block: {
      type: "many-to-one",
      target: "Block",
      joinColumn: { name: "block_id", referencedColumnName: "id" },
      nullable: true,
      onDelete: "SET NULL",
      onUpdate: "NO ACTION",
    },
    bill: { type: "one-to-many", target: "Bill", inverseSide: "booking" },
  },
});