import { EntitySchema } from "typeorm";

export default new EntitySchema({
  name: "Property",
  tableName: "properties",
  columns: {
    id: { type: "uuid", primary: true, generated: "uuid" },
    propertyname: { type: "varchar", nullable: true },
    typeId: { name: "type_id", type: "uuid", nullable: true },
    description: { type: "text", nullable: true },
    files: { type: "text", array: true, nullable: true },
    address: { type: "text", nullable: true },
    zipcode: { type: "varchar", nullable: true },
    maintencanceHistory: {
      name: "maintencance_history",
      type: "jsonb",
      nullable: true,
    },
    maplink: { type: "text", nullable: true },
    rent: { type: "numeric", nullable: true },
    area: { type: "numeric", nullable: true },
    isDeleted: { name: "is_deleted", type: "boolean", default: false },
    ownerId: { name: "owner_id", type: "uuid", nullable: true },
    tenantId: { name: "tenant_id", type: "uuid", nullable: true },
    projectId: { name: "project_id", type: "uuid", nullable: true },
    blockId: { name: "block_id", type: "uuid", nullable: true },
    accountName: { name: "account_name", type: "varchar", nullable: true },
    companyId: { name: "company_id", type: "uuid", nullable: true },
    isVacant: { name: "is_vacant", type: "boolean", default: true },
    createdAt: { name: "created_at", type: "timestamp", createDate: true },
    updatedAt: { name: "updated_at", type: "timestamp", updateDate: true },
  },

  relations: {
    type: {
      type: "many-to-one",
      target: "Type",
      joinColumn: { name: "type_id", referencedColumnName: "id" },
      nullable: true,
      onDelete: "SET NULL",
      onUpdate: "NO ACTION",
    },
    owner: {
      type: "many-to-one",
      target: "Owner",
      joinColumn: { name: "owner_id", referencedColumnName: "id" },
      nullable: true,
      onDelete: "SET NULL",
      onUpdate: "NO ACTION",
    },
    tenant: {
      type: "many-to-one",
      target: "Tenant",
      joinColumn: { name: "tenant_id", referencedColumnName: "id" },
      nullable: true,
      onDelete: "SET NULL",
      onUpdate: "NO ACTION",
    },
    project: {
      type: "many-to-one",
      target: "project",
      joinColumn: { name: "project_id", referencedColumnName: "id" },
      nullable: true,
      onDelete: "SET NULL",
      onUpdate: "NO ACTION",
    },
    block: {
      type: "many-to-one",
      target: "Block",
      joinColumn: { name: "block_id", referencedColumnName: "id" },
      nullable: true,
      onDelete: "SET NULL",
      onUpdate: "NO ACTION",
    },
    company: {
      type: "many-to-one",
      target: "Company",
      joinColumn: { name: "company_id", referencedColumnName: "id" },
      nullable: true,
      onDelete: "RESTRICT",
      onUpdate: "NO ACTION",
    },
    bookings: { type: "one-to-many", target: "Booking", inverseSide: "property" },
    bills: { type: "one-to-many", target: "Bill", inverseSide: "property" },
    complaints: { type: "one-to-many", target: "Complaint", inverseSide: "property" },
    propertyImages: { type: "one-to-many", target: "PropertyImg", inverseSide: "property" },
    accountsReceivable: {
      type: "one-to-many",
      target: "AccountsReceivable",
      inverseSide: "property",
    },
    generalBills: { type: "one-to-many", target: "GeneralBill", inverseSide: "property" },
  },
});