import { EntitySchema } from "typeorm";

export default new EntitySchema({
  name: "UnifiedVoucher",
  tableName: "unified_vouchers",
  columns: {
    id: { type: "uuid", primary: true, generated: "uuid" },
    voucherNo: { name: "voucher_no", type: "varchar", nullable: false, unique: true },
    voucherType: {
      name: "voucher_type",
      type: "enum",
      enum: ["AR", "AP", "REC", "PAY", "PUR", "SAL", "MDN", "JV", "CN", "PU", "SP", "GB"],
      nullable: false,
    },
    sourceDocument: { name: "source_document", type: "jsonb", nullable: true },
    companyId: { name: "company_id", type: "uuid", nullable: false },
    date: { type: "timestamp", default: () => "CURRENT_TIMESTAMP" },
    month: { type: "varchar", nullable: false },
    particulars: { type: "text", nullable: false },
    debit: { type: "jsonb", nullable: false },
    credit: { type: "jsonb", nullable: false },
   amount: {
  type: "numeric",
  precision: 12,
  scale: 2,
  nullable: false,
},
    paymentStatus: {
      name: "payment_status",
      type: "enum",
      enum: ["pending", "partial", "partially_paid", "paid", "overdue"],
      nullable: true,
    },
    dueDate: { name: "due_date", type: "timestamp", nullable: true },
    propertyId: { name: "property_id", type: "uuid", nullable: true },
    propertyName: { name: "property_name", type: "varchar", nullable: true },
    status: {
      type: "enum",
      enum: ["draft", "pending", "approved", "rejected", "cancelled"],
      default: "draft",
    },
    approvedBy: { name: "approved_by", type: "uuid", nullable: true },
    approvedAt: { name: "approved_at", type: "timestamp", nullable: true },
    linkedVouchers: { name: "linked_vouchers", type: "jsonb", nullable: true },
    outstandingAmount: {
  name: "outstanding_amount",
  type: "numeric",
  precision: 12,
  scale: 2,
  nullable: true,
},
    surchargeAmount: {
  name: "surcharge_amount",
  type: "numeric",
  precision: 12,
  scale: 2,
  default: 0,
},

   totalAmountOwed: {
  name: "total_amount_owed",
  type: "numeric",
  precision: 12,
  scale: 2,
  nullable: true,
},
    lastPaymentAmount: {
  name: "last_payment_amount",
  type: "numeric",
  precision: 12,
  scale: 2,
  default: 0,
},
    lastPaymentDate: { name: "last_payment_date", type: "timestamp", nullable: true },
    paymentHistory: { name: "payment_history", type: "jsonb", nullable: true },
    tags: { type: "text", array: true, nullable: true },
    details: { type: "text", nullable: true },
    isDeleted: { name: "is_deleted", type: "boolean", default: false },
    createdAt: { name: "created_at", type: "timestamp", createDate: true },
    updatedAt: { name: "updated_at", type: "timestamp", updateDate: true },
  },
  indices: [
    {
      name: "IDX_unified_vouchers_company_type_payment",
      columns: ["companyId", "voucherType", "paymentStatus"],
    },
    { name: "IDX_unified_vouchers_company_date", columns: ["companyId", "date"] },
    { name: "IDX_unified_vouchers_property_month", columns: ["propertyId", "month"] },
    {
      name: "IDX_unified_vouchers_company_month_type",
      columns: ["companyId", "month", "voucherType"],
    },
  ],

  relations: {
    company: {
      type: "many-to-one",
      target: "Company",
      joinColumn: { name: "company_id", referencedColumnName: "id" },
      onDelete: "RESTRICT",
      onUpdate: "NO ACTION",
    },
    property: {
      type: "many-to-one",
      target: "Property",
      joinColumn: { name: "property_id", referencedColumnName: "id" },
      nullable: true,
      onDelete: "RESTRICT",
      onUpdate: "NO ACTION",
    },
    approvedBy: {
      type: "many-to-one",
      target: "User",
      joinColumn: { name: "approved_by", referencedColumnName: "id" },
      nullable: true,
      onDelete: "SET NULL",
      onUpdate: "NO ACTION",
    },
  },
});